import re

print("Plan: ")
print("1. Implement Jitter Pass")
print("   Iterate through boundaries of SECTOR_CAVERN (or similar sectors) and apply random offset (-1 to +1 tile) to boundary walls.")
print("   This breaks up straight horizontal/vertical walls.")
print("   We can do this inside cave_gen, after room generation and before stream generation.")
print("   Actually, a simpler approach is to iterate over the entire map, and if a wall tile is adjacent to a floor tile, maybe move it.")
print("   Wait, the instructions say 'iterate through sector-boundary wall tiles and apply a small random offset'. ")
print("   Wait, 'sector-boundary wall tiles'.")
print("2. Add Cellular Automata Smoothing Pass")
print("   Create a 'Cave Smoothing' routine.")
print("   Run 2-3 iterations specifically on the edges of 'cavernous' sectors to soften boxiness.")
print("   If a wall has 5+ floor neighbors, turn it to floor.")
print("   If a floor has 5+ wall neighbors, turn it to wall.")
print("3. Implement Drunkard's Walk for Elemental Streams")
print("   Modify build_streamer2 or create a new agent-based stream generator.")
print("   Pick starting coordinate and life value.")
print("   Agent moves randomly, carving out element.")
print("   If Acid, avoid destroying critical stairs/artifacts but eat through walls.")
print("   10% chance to overflow into an adjacent sector.")
