#include <stdio.h>
#include <string.h>

typedef const char* cptr;

static cptr s_info_attack_types[] = {
	"",
	"NOTHING",
	"ARROW",
	"MISSILE",
	"MANA",
	"HOLY_ORB",
	"LITE_WEAK",
	"DARK_WEAK",
	"WATER",
	"PLASMA",
	"METEOR",
	"ICE",
	"GRAVITY",
	"INERTIA",
	"FORCE",
	"TIME",
	"ACID",
	"ELEC",
	"FIRE",
	"COLD",
	"POIS",
	"XXX2",
	"LITE",
	"DARK",
	"XXX3",
	"CONFUSION",
	"SOUND",
	"SHARD",
	"NEXUS",
	"NETHER",
	"CHAOS",
	"DISENCHANT",
	"XXX4",
	"KILL_WALL",
	"KILL_DOOR",
	"KILL_TRAP",
	"MAKE_WALL",
	"MAKE_DOOR",
	"MAKE_TRAP",
	"MAKE_GLYPH",
	"MAKE_STAIR",
	"AWAY_UNDEAD",
	"AWAY_EVIL",
	"AWAY_ALL",
	"TURN_UNDEAD",
	"TURN_EVIL",
	"TURN_ALL",
	"DISP_UNDEAD",
	"DISP_EVIL",
	"DISP_ALL",
	"WORD_OF_DESTRUCTION",
	"CLONE",
	"POLY",
	"HEAL",
	"SPEED",
	"SLOW",
	"CONF",
	"SLEEP",
	"DRAIN",
	"QUAKE",
	"WALL_TO_CHAOS",
	"MIND_BLAST",
	"BRAIN_SMASH",
	"CHAOS_DESTRUCTION",
	"EARTHQUAKE",

	"AWAY_ALL_VERT",
	"RECALL",
	"ALTER",
	"DETECT_DOOR",
	"DETECT_TRAP",
	"DETECT_STAIR",
	"DETECT_TREASURE",
	"DETECT_GOLD",
	"DETECT_OBJECT",
	"DETECT_MAGIC",
	"DETECT_MONSTER",
	"DETECT_INVIS",
	"DETECT_EVIL",
	"DETECT_ANY",
	"HEAL_INSANITY",
	"HEAL_FEAR",
	"HEAL_CUT",
	"HEAL_STUN",
	"HEAL_POISON",
	"HEAL_DEX",
	"HEAL_CHR",
	"HEAL_STR",
	"HEAL_CON",
	"HEAL_WIS",
	"HEAL_INT",
	"HEAL_LIFE",
	"SHIELD",
	"HEROISM",
	"BLESS",
	"FOOD",
	"UNCURSE",
	"RECHARGE",
	"HEAVY_UNCURSE",
	"IDENT",
	"HEAVY_IDENT",
	"SUPER_IDENT",
	"RES_FIRE",
	"RES_COLD",
	"RES_ELEC",
	"RES_ACID",
	"RES_POIS",
	"GENOCIDE",
	"MASS_GENOCIDE",
	"ENCHANT_TO_HIT",
	"ENCHANT_TO_DAM",
	"ENCHANT_AC",
	"BRAND_AMMO",
	"BRAND_WEAPON",
	"MAKE_MONSTER",
	"MAKE_PET",
	"HEAL_CONF",
	"DETECT_GRIDS",
	"PROT_EVIL",
	"RING_OF_POWER",
	"HEAL_BLIND",
	"WAKE",
	"CURSE_ARMOR",
	"CURSE_WEAPON",
	"LEARN_RECIPE",
	"ENCHANT_EGO_ITEM",
	"ENCHANT_ARTIFACT",
	"MAKE_ITEM",
	"RUINATION",
	"DEC_STR",
	"DEC_INT",
	"DEC_WIS",
	"DEC_DEX",
	"DEC_CON",
	"DEC_CHR",
	"INFRA",
	"SEE_INVIS",
	"BERSERK",
	"HEAL_MANA",
	"INC_STR",
	"INC_INT",
	"INC_WIS",
	"INC_DEX",
	"INC_CON",
	"INC_CHR",
	"HEAL_MUTATION",
	"CAUSE_MUTATION",
	"CAUSE_INSANITY",
	"CAUSE_FEAR",
	"CAUSE_CUT",
	"CAUSE_STUN",
	"CAUSE_POISON",
	"HEAL_HALLUC",
	"CAUSE_HALLUC",
	"GAIN_EXP",
	"GLOWING_HANDS",
	"CAUSE_CONF",
	"CAUSE_BLIND",
	"RANDOM",
	"MINUS_FOOD",
	"RAISE_DEAD",
	"SOUL_PRISON",
	"REPAIR",
	"TRANSMUTE",
	"HEAVY_TRANSMUTE",
	"MAKE_PET_SCALING",
	"TELEKINESIS",
	NULL
};

static int grab_number(char *line, cptr arr[])
{
	int i;

	for (i = 0; arr[i] != NULL; i++)
	{
		if (strcmp(line, arr[i]) == 0)
			return i;
	}
	return -1;
}

int main() {
    int idx = grab_number("TELEKINESIS", s_info_attack_types);
    printf("Index of TELEKINESIS: %d\n", idx);
    int idx_force = grab_number("FORCE", s_info_attack_types);
    printf("Index of FORCE: %d\n", idx_force);
    return 0;
}
